### ISSUE TITLE
Limit available AMI for Scylla

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#12]
As an alternative to #10 we can limit the instance AMI can run on, similar to what DS AMI 
![image](https://cloud.githubusercontent.com/assets/170200/12121631/e2cb23fa-b3de-11e5-80f5-0f47b65c830d.png)

**Comment by slivne** [comment]
I think this is deon via
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-for-amazon-ec2.html

http://stackoverflow.com/questions/23727280/how-to-limit-instance-launch-by-instance-type-in-aws-using-iam-service

and I agree lets limit the AMI to c3.X and i2.X for the time being

**Comment by syuu1228** [comment]
I tried IAM policy to limit instance type, but it seems not for our purpose.
I guess this is for limiting start/stop instances from EC2 instances via 'aws' command (or the API), not for limiting instance type on instance creation wizard.
Why DS AMI seems able to limit instance is, because it's 'Instance Store-Backed AMI'. On the AMI, root disk is ephemeral, not able to stop & restart. You can terminate instance, but not able to recover.
Since m4/c4 (and some other instance types) are EBS only, you are not able to run such AMI on the type.

So we also can make our AMI as Instance Store-Backed to limiting instance type, but user cannot keep their root disk beyond shutdown. And we already discuss that, and I think the answer was use EBS-Backed AMI.

Note that we can make two AMIs: one for developing - EBS Backed, other one for users - Instance Store-Backed.

**Comment by syuu1228** [comment]
Comments?

**Comment by avikivity** [comment]
Since #10 was fixed, should we do this at all?

**Comment by tzach** [comment]
Closing. Scylla support all instances, either as "optimzed" or "run scylla_setup"
