### ISSUE TITLE
Possible performance degradation using all CPUs in small instances

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-ami#21]
Based on testing completed on C3.2xl instances. the CPU info is:
[centos@ip-172-31-27-168 ~]$ cat /etc/scylla.d/cpuset.conf
CPUSET="--cpuset 0-7 "

It possible that vCPU 0 usage cause performance degradation due to IRQ balancing.
/cc @glommer

**Comment by glommer** [comment]
This happens because the network script wrongly configures the instance in MQ instead of SQ mode. Vlad and myself are working on a fix for the main Scylla rpm, and the AMI should be updated as soon as this is fixed.

A temporary workaround is to configure the network manually in SQ mode and then adjust the cpuset manually to 1-7.

**Comment by tzach** [comment]
> A temporary workaround is to configure the network manually in SQ mode

How do you do that?

**Comment by glommer** [comment]
for the cpuset, just change it manually to 1-7 in cpuset.conf.
That will already bring most of the performance back.

As an extra step:
```
sudo sh /usr/lib/scylla/posix_net_conf.sh -sq 
sudo sed -i "s/SET_NIC=yes/SET_NIC=no/" /etc/sysconfig/scylla-server
```

The only problem is that `posix_net_conf.sh -sq` would have to be re-executed at every VM boot.

**Comment by tzach** [comment]
@glommer is this still relevant?

**Comment by glommer** [comment]
no

please close
