### ISSUE TITLE
Support --release <release_version> for Scylla

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#3]
Scylla AMI always use latest stable release.
Cassandra AMI allow using earlier versions with an optional release parameter[1]
```
--release <release_version>
    Allows for the installation of a previous DSE version
    Example: 1.0.2
    Default: Ignored
```
Support earlier version is useful for regression tests.

[1] https://github.com/riptano/ComboAMI#advanced

**Comment by slivne** [comment]
Our repos (fedora/centos/ubuntu) currently do not support versions - we
need to add support for that to make this happen - so this is not a
"scylla-ami" only item.

A different flag that we do want to add for internal use / outsider trying
latest version is something like --repo (path to a unstable repo) so that
repo will be used instead of the default

**Comment by tzach** [comment]
@slivne good point
I created new issues as you suggested
* #4
* https://github.com/scylladb/scylla/issues/627

**Comment by syuu1228** [comment]
Same as #4, we can't choose both 'specify package version on userdata parameter' and 'pre-install packages'.

**Comment by slivne** [comment]
We will not support it for GA
