### ISSUE TITLE
Support --repository <repository> for Scylla

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#4]
Scylla AMI always use one repo
Cassandra AMI allow using other repos with an optional release parameter[1]
```
--repository <repository>
    Allows you to set a custom repository to pull configuration files from
    Default: none, falls back to repository used to create the AMI
```
Support other repos is useful for regression tests.

[1] https://github.com/riptano/ComboAMI#advanced

**Comment by syuu1228** [comment]
I think It only works well on origin implementation.
Because it's installing origin packages on AMI instance first boot.
We are pre-installing our packages on AMI image.
In this way, we should distribute AMIs per version.
We can change current approach to origin way, but do we want to do that or not?

**Comment by slivne** [comment]
No the decision for GA is to leave as is - the AMI is prepacakaged ... I'll
update the issue
